name: Builds

on:
  push: { branches: [main] }
  pull_request:
    paths-ignore:
      - '.github/**'
 
jobs:
  buildForAllPlatformsUbuntu:
    name: Build ${{ matrix.targetPlatform }} #on ${{ matrix.unityVersion }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        projectName:
          - HDRP
        #cloudRunnerCluster:
        #  - local-docker
        #  - local
        #projectPath:
        #  - test-project
        # unityVersion:
          # - 2022.2.2f1          
          # - 2022.2.1f1
          # - 2021.3.16f1
        targetPlatform:
        #  - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        #  - StandaloneLinux64 # Build a Linux 64-bit standalone.
        #  - iOS # Build an iOS player.
          # - Android # Build an Android .apk.
          # - WebGL # WebGL.
          #          - StandaloneWindows # Build a Windows standalone.
          #          - WSAPlayer # Build an Windows Store Apps player.
          #          - PS4 # Build a PS4 Standalone.
          #          - XboxOne # Build a Xbox One Standalone.
          #          - tvOS # Build to Apple's tvOS platform.
          #          - Switch # Build a Nintendo Switch player
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectName }}-ubuntu-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          restore-keys: |
            Library-${{ matrix.projectName }}-ubuntu-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectName }}-ubuntu-
            Library-

      ###########################
      #          Build          #
      ###########################
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.EMAIL }}
          UNITY_PASSWORD: ${{ secrets.PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:          
          #projectPath: ${{ matrix.projectPath }}
          #unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ matrix.projectName }}
          buildMethod: UnityBuilderAction.BuildScript.Build
          #customParameters: -profile SomeProfile -someBoolean -someValue exampleValue
          #cloudRunnerCluster: ${{ matrix.cloudRunnerCluster }}          
          allowDirtyBuild: true

      ###########################
      #          Upload         #
      ###########################
      - uses: actions/upload-artifact@v2
        with:
          name: Build ${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: 14
          
      # - uses: Difegue/action-megacmd@master
        # with:
          # args: put -c build/${{ matrix.targetPlatform }} /Unity_projects/${{ matrix.projectName }}/ #${{ matrix.unityVersion }}_2/
        # env:
          # USERNAME: ${{ secrets.MEGA_USERNAME }}
          # PASSWORD: ${{ secrets.MEGA_PASSWORD }}
          